version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3360:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data:
